### ISSUE TITLE
Running user defined Python Script fails(?)

### ISSUE THREAD

**Issue by haruotsa** [seemoo-lab/chirpotle#3]
I leave this as another Issue as is it somewhat disconnected from the previous one.

I'm not sure if this is a bug/feature: When I copy paste the example alice-bob communication script to a Python file (example.py) and adjust the node names as configured in my testconf the command "./chirpotle.sh run --conf testconf example.py" fails (Cannot find variable bob). Am I missing something here? 

btw: I'm looking forward to use Chirpotle to test reactive jamming on a LoRaWAN end-device. Is there by chance a script included, which I could use as a template to perform my own experiments?

**Comment by fhessel** [comment]
> When I copy paste the example alice-bob communication script to a Python file (example.py) and adjust the node names as configured in my testconf the command "./chirpotle.sh run --conf testconf example.py" fails (Cannot find variable bob). Am I missing something here?

You are missing something, but the documentation is missing it too, or at least should be more explicit about it. `./chirpotle.sh interactive` will [register all nodes from your config as global variables](https://github.com/seemoo-lab/chirpotle/blob/main/scripts/interactive-session.py) and print them so you know what's there. `./chirpotle.sh run` doesn't do that, it only executes the script within the environment needed to run the framework (idea is to have no magic in the scripts). So you would need to do this in the beginning:

```python
from chirpotle.context import tpy_from_context

tc, devices = tpy_from_context()
alice_lora = tc.nodes['alice']['lora']
bob_lora   = tc.nodes['bob']['lora']
```

In this case `alice` is referring to a node called alice, and `bob` is referring to a node called bob in the controller configuration. Each of the node has a single module connected to it, called `lora`. In an interactive session, node and module name are concatenated to create the global variable name (so `lora` on `alice` will be `alice_lora` in global scope) – that's where the names in the example are coming from.

If you don't mind using notebooks, try running `./chirpotle.sh notebook --conf testconf`, the examples there are more comprehensive and should be working. The intention is to make that a tutorial that you can easily re-run on your machine, and it also allows you to directly create figures from you experiment using `matplotlib`.

> btw: I'm looking forward to use Chirpotle to test reactive jamming on a LoRaWAN end-device. Is there by chance a script included, which I could use as a template to perform my own experiments?

Not yet, apart from inherent reactive jamming as foundation for the [wormhole attacks](https://github.com/seemoo-lab/chirpotle/blob/2063c7d0e977df1e40d8344b9210f3d3b433678d/controller/chirpotle/chirpotle/tools/wormhole.py#L554-L564) in the WiSec '20 paper. I have some notebooks here with reactive jamming experiments. I'll convert one into a tutorial chapter similar to the notebook for triggered jamming and push it.

**Comment by haruotsa** [comment]
Ok, I got it! I'll also have a look on the notebooks. I really appreciate your guidance here as well as the efforts to refine the framework. Thank you!

**Comment by fhessel** [comment]
Sorry that it took some time. I wanted to verify that it's working, but the setup for reactive jamming and sniffing is sometimes a bit complicated for its scale. However, [this notebook](https://github.com/seemoo-lab/chirpotle/blob/484e7520a81a7a76640d762ad162e9f544d82fc5/templates/notebook/examples/03-reactive-jamming.ipynb) now contains the basics, you can just copy it to your `notebook` folder in the repository root, if that already exists after running `chirpotle.sh notebook`. All but the last experiment should work with three devices in the same room as well.

**Comment by haruotsa** [comment]
No worries, I checked the notebook and it looks sound! Looking forward to run the experiments.

**Comment by haruotsa** [comment]
As I'm now also able to interact with the nodes via python code, I close this issue.
